# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JL_detail_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('stat_cost', models.CharField(max_length=50, verbose_name='消耗')),
                ('bid', models.CharField(max_length=50, verbose_name='出价(元）')),
                ('ad_budget', models.CharField(max_length=50, verbose_name='计划预算(元)')),
                ('show_cnt', models.CharField(max_length=50, verbose_name='展示数')),
                ('cpm_platform', models.CharField(max_length=50, verbose_name='平均千次展现')),
                ('click_cnt', models.CharField(max_length=50, verbose_name='点击数')),
                ('cpc_platform', models.CharField(max_length=50, verbose_name='平均单价')),
                ('ctr', models.CharField(max_length=50, verbose_name='点击率')),
                ('ad_id', models.CharField(max_length=50, verbose_name='ad_id')),
                ('convert_cnt', models.CharField(max_length=50, verbose_name='转化数')),
                ('conversion_cost', models.CharField(max_length=50, verbose_name='转化成本')),
                ('conversion_rate', models.CharField(max_length=50, verbose_name='转化率')),
                ('aadvid', models.CharField(max_length=50, verbose_name='广告客户id')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'JL_detail_data',
                'verbose_name': '巨量详情数据',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JL_Time_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('deep_convert_rate', models.CharField(max_length=50, verbose_name='深度转化率')),
                ('cost', models.CharField(max_length=50, verbose_name='消耗')),
                ('conversion_rate', models.CharField(max_length=50, verbose_name='转化率')),
                ('deep_convert_cnt', models.CharField(max_length=50, verbose_name='深度转化数')),
                ('cpc_platform', models.CharField(max_length=50, verbose_name='平均点击单价')),
                ('advertiser_id', models.CharField(max_length=50, verbose_name='广告客户唯一标识')),
                ('deep_convert_cost', models.CharField(max_length=50, verbose_name='深度转化成本')),
                ('cpm_platform', models.CharField(max_length=50, verbose_name='平均千次展示')),
                ('ctr', models.CharField(max_length=50, verbose_name='点击率')),
                ('stat_time_hour', models.CharField(max_length=50, verbose_name='时间')),
                ('ad_id', models.CharField(max_length=50, verbose_name='广告客户id')),
                ('conversion_cost', models.CharField(max_length=50, verbose_name='转化成本')),
                ('show_cnt', models.CharField(max_length=50, verbose_name='展示数')),
                ('convert_cnt', models.CharField(max_length=50, verbose_name='转化数')),
                ('click_cnt', models.CharField(max_length=50, verbose_name='点击数')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'JL_time_data',
                'verbose_name': '巨量时段数据',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('stat_cost', models.CharField(max_length=50, verbose_name='消耗')),
                ('conversion_rate', models.CharField(max_length=50, verbose_name='转化率')),
                ('cpc_platform', models.CharField(max_length=50, verbose_name='平均点击单价')),
                ('deep_convert_rate', models.CharField(max_length=50, verbose_name='深度转化率')),
                ('deep_convert_cost', models.CharField(max_length=50, verbose_name='深度转化成本')),
                ('convert_cnt', models.CharField(max_length=50, verbose_name='转化数')),
                ('cpm_platform', models.CharField(max_length=50, verbose_name='平均千次展示')),
                ('show_cnt', models.CharField(max_length=50, verbose_name='点击率')),
                ('ctr', models.CharField(max_length=50, verbose_name='点击数')),
                ('conversion_cost', models.CharField(max_length=50, verbose_name='转化成本')),
                ('deep_convert_cnt', models.CharField(max_length=50, verbose_name='深度转化数')),
                ('advertiser_id', models.CharField(max_length=50, verbose_name='广告客户id')),
                ('advertiser_role', models.CharField(max_length=50, verbose_name='账号')),
                ('advertiser_balance', models.CharField(max_length=50, verbose_name='账户余额')),
                ('advertiser_valid_balance', models.CharField(max_length=50, verbose_name='账户可用余额')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'jldata',
                'verbose_name': '巨量数据',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(verbose_name='巨量cookie')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'jluser',
                'verbose_name': '巨量账户',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tb_detail_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price_sort', models.CharField(max_length=255, verbose_name='全部销售额')),
                ('used_income', models.CharField(max_length=255, verbose_name='有效佣金')),
                ('all_income_sort', models.CharField(max_length=255, verbose_name='全部佣金')),
                ('spayallorder', models.CharField(max_length=255, verbose_name='有效单数')),
                ('time_format', models.CharField(max_length=255)),
                ('allorder', models.CharField(max_length=255, verbose_name='全部单数')),
                ('create', models.CharField(max_length=255)),
                ('adzone_id', models.CharField(max_length=255)),
                ('jl_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossapp.JL_Time_date')),
            ],
            options={
                'db_table': 'Tb_detail_data',
                'verbose_name': '淘宝详情数据',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tbdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price', models.CharField(max_length=255, verbose_name='全部销售额')),
                ('allorder', models.CharField(max_length=255, verbose_name='全部单数')),
                ('usedorder', models.CharField(max_length=255, verbose_name='有效单数')),
                ('all_income_sort', models.CharField(max_length=255, verbose_name='全部佣金')),
                ('used_income_sort', models.CharField(max_length=255, verbose_name='有效佣金')),
                ('campaignName', models.CharField(max_length=255)),
                ('create', models.DateTimeField()),
                ('adzone_id', models.CharField(max_length=50)),
                ('jl_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossapp.Jldata')),
            ],
            options={
                'db_table': 'tbdata',
                'verbose_name': '淘宝数据',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tbuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(verbose_name='抖老板cookie')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbuser',
                'verbose_name': '淘宝账户',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wmuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('pwd', models.CharField(max_length=150, verbose_name='密码')),
                ('create', models.DateTimeField()),
            ],
            options={
                'db_table': 'wmuser',
                'verbose_name': '本站用户表',
                'managed': True,
            },
        ),
    ]
